---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      -[0-9]+\.[0-9]+\.[0-9]+
jobs:
  ci:
    name: Run checks, tests, and docs over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [20.3, 21.3, 22.3, 23.1, 24.0, 25.1]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: make
