---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    tags:
      -[0-9]+\.[0-9]+\.[0-9]+
jobs:
  ci:
    name: test otp ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    container:
      image: erlang:${{matrix.otp_vsn}}
    strategy:
      matrix:
        otp_vsn: [20, 21, 22, 23, 24, 25, 26, 27]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - run: make
